version: "3.6"

services:
  entry:
    image: nginx:1.17.8
    container_name: auth1-nginx
    networks:
      - subnet
    depends_on:
      - hydra
      - auth1
    ports:
      - "7001:80"
      - "6060:6060"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - DEBUG_PORT=6060
      - AUTHONE_SERVER=http://auth1:8080
      - AUTHONE_DEBUG=http://auth1:6060
      - HYDRA_SERVER=http://hydra:4444
      - WEB_SERVER=http://auth1-web:80
      - CENTRIFUGO_SERVER=http://centrifugo:8000
      - DOLLAR=$$
    volumes:
      - ./etc/nginx/default.template:/etc/nginx/conf.d/default.template
    command: bin/bash -c " envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  web:
    image: p1hub/store-auth-web:master
    container_name: auth1-web
    networks:
      - subnet

  hydra-migrate:
    image: oryd/hydra:v1.3.2
    container_name: hydra-migrate
    depends_on:
      - auth1-postgres
    networks:
      - subnet
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://hydra:secret@auth1-postgres/hydra?sslmode=disable
      - SYSTEMS_SECRET=newYouReallyNeedToChangeThis youReallyNeedToChangeThis
      - SECRETS_COOKIE=newYouReallyNeedToChangeThis youReallyNeedToChangeThis
    restart: on-failure
    command: "migrate sql postgres://hydra:secret@auth1-postgres/hydra?sslmode=disable --yes"

  hydra:
    image: oryd/hydra:v1.3.2
    container_name: hydra
    depends_on:
      - hydra-migrate
    networks:
      - subnet
    environment:
      - DSN=postgres://hydra:secret@auth1-postgres/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://localhost:7001
      - URLS_SELF_PUBLIC=http://localhost:7001
      - URLS_CONSENT=http://localhost:7001/oauth2/consent
      - URLS_LOGIN=http://localhost:7001/api/login
      - URLS_ERROR=http://localhost:7001/error
      - URLS_POST_LOGOUT_REDIRECT=http://localhost:7001/oauth2/logout
      - LOG_LEVEL=debug
      - OAUTH2_HASHERS_BCRYPT_COST=8
      - SECRETS_SYSTEM=newYouReallyNeedToChangeThis youReallyNeedToChangeThis
      - SECRETS_COOKIE=newYouReallyNeedToChangeThis youReallyNeedToChangeThis
      - TTL_ACCESS_TOKEN=3h
      - TTL_REFRESH_TOKEN=720h
    restart: unless-stopped
    command: "serve all --dangerous-force-http"

  auth1-mongo:
    image: mongo:4.1.3
    container_name: auth1-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    networks:
      - subnet
    volumes:
      - auth1-mongo:/data/db

  auth1-postgres:
    image: postgres:10.5
    container_name: auth1-postgres
    restart: unless-stopped
    networks:
      - subnet
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    volumes:
      - auth1-postgres:/data/postgres

  auth1-redis:
    image: redis:5.0.3
    container_name: auth1-redis
    restart: unless-stopped
    networks:
      - subnet
    volumes:
      - auth1-redis:/data/redis

  auth1-mailtrap:
    image: eaudeweb/mailtrap
    container_name: auth1-mailtrap
    ports:
      - "8001:80"
    networks:
      - subnet
    environment:
      - MT_USER=test
      - MT_PASSWD=test

  geoip:
    image: p1hub/p1geoip:master
    networks:
      - subnet    

  centrifugo:
    image: centrifugo/centrifugo:v2.4.0
    container_name: centrifugo
    restart: unless-stopped
    networks:
      - subnet
    volumes:
      - ./etc/centrifugo:/centrifugo
    command: "centrifugo -c config.yml"

  build:
    image: p1hub/qilinauth-qilin:master
    build: .
    command: echo build successful

  auth1:
    image: p1hub/qilinauth-qilin:master
    restart: unless-stopped
    depends_on:
      - auth1-mongo
      - auth1-redis
      - auth1-mailtrap
      - hydra
    networks:
      - subnet
    ports:
      - 5301:5300
    environment:
      - AUTHONE_LOGGING_DEV=true
      - AUTHONE_SERVER_PORT=8080
      - AUTHONE_DATABASE_HOST=auth1-mongo
      - AUTHONE_DATABASE_NAME=auth-one
      - AUTHONE_REDIS_ADDRESS=auth1-redis:6379
      - AUTHONE_HYDRA_PUBLIC_URL=http://hydra:4444
      - AUTHONE_HYDRA_ADMIN_URL=http://hydra:4445
      - AUTHONE_SESSION_NETWORK=tcp
      - AUTHONE_SESSION_ADDRESS=auth1-redis:6379
      - AUTHONE_MIGRATION_DIRECT=up
      - AUTHONE_RECAPTCHA_KEY=6Lea_dUUAAAAAGV4L8JS7NSgmjOZjafXkS4flPEK
      - AUTHONE_RECAPTCHA_SECRET=6Lea_dUUAAAAAK294XwQmOIujxW8ssNRk_zWU5AB
      - AUTHONE_RECAPTCHA_HOSTNAME=localhost
      - AUTHONE_MAILER_HOST=auth1-mailtrap
      - AUTHONE_MAILER_PORT=25
      - AUTHONE_MAILER_REPLY_TO=noreply@example.com
      - AUTHONE_MAILER_FROM=noreply@example.com
      - AUTHONE_CENTRIFUGO_ADDR=http://centrifugo:8000
      - AUTHONE_CENTRIFUGO_API_KEY=insecure
      - AUTHONE_CENTRIFUGO_HMAC_SECRET=insecure
      - AUTHONE_CENTRIFUGO_SESSION_TTL=1200
      - AUTHONE_CENTRIFUGO_LAUNCHER_CHANNEL=launcher

  admin:
    image: p1hub/qilinauth-qilin:master
    command: /app/auth1 admin
    restart: unless-stopped
    depends_on:
      - auth1-mongo
      - auth1-redis
    networks:
      - subnet
    ports:
      - 6001:8081
    environment:
      - AUTHONE_LOGGING_DEV=true
      - AUTHONE_DATABASE_HOST=auth1-mongo
      - AUTHONE_DATABASE_NAME=auth-one
      - AUTHONE_REDIS_ADDRESS=auth1-redis:6379

volumes:
  auth1-mongo:
  auth1-redis:
  auth1-postgres:

networks:
  subnet:
