version: "3.6"

services:
  web:
    image: nginx
    container_name: auth1-nginx
    networks:
      - subnet
    depends_on:
      - hydra
      - auth1
    ports:
      - "80:80"
      - "6060:6060"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - DEBUG_PORT=6060
      - AUTHONE_SERVER=http://auth1:8080
      - AUTHONE_DEBUG=http://auth1:6060
      - HYDRA_SERVER=http://hydra:4444
    volumes:
      - ./etc/nginx/default.template:/etc/nginx/conf.d/default.template
    command: bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  hydra-migrate:
    image: oryd/hydra:v1.0.0-rc.6_oryOS.10-alpine
    container_name: hydra-migrate
    depends_on:
      - auth1-postgres
    networks:
      - subnet
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://hydra:secret@auth1-postgres/hydra?sslmode=disable
      - SYSTEM_SECRET=youReallyNeedToChangeThis
    restart: on-failure
    command: "migrate sql -e"

  hydra:
    image: oryd/hydra:v1.0.0-rc.6_oryOS.10-alpine
    container_name: hydra
    depends_on:
      - hydra-migrate
    networks:
      - subnet
    environment:
      - DATABASE_URL=postgres://hydra:secret@auth1-postgres/hydra?sslmode=disable
      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://localhost
      - OAUTH2_CONSENT_URL=http://localhost/oauth2/consent
      - OAUTH2_LOGIN_URL=http://localhost/oauth2/login
      - BCRYPT_COST=8
      - ACCESS_TOKEN_LIFESPAN=3h
      - REFRESH_TOKEN_LIFESPAN=720h
      - SYSTEM_SECRET=youReallyNeedToChangeThis
    restart: unless-stopped
    command: "serve all --dangerous-force-http"

  auth1-mongo:
    image: mongo:4.1.3
    container_name: auth1-mongo
    restart: unless-stopped
    networks:
      - subnet
    volumes:
      - auth1-mongo:/data/db

  auth1-postgres:
    image: postgres:10.5
    container_name: auth1-postgres
    restart: unless-stopped
    networks:
      - subnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    volumes:
      - auth1-postgres:/data/postgres

  auth1-redis:
    image: redis:5.0.3
    container_name: auth1-redis
    restart: unless-stopped
    networks:
      - subnet
    volumes:
      - auth1-redis:/data/redis

  auth1:
    image: golang:1.11.5-stretch
    container_name: auth1
    restart: unless-stopped
    depends_on:
      - auth1-mongo
      - auth1-redis
      - hydra
    networks:
      - subnet
    volumes:
      - .:/go/src/auth-one
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/auth-one
    command: go run main.go server
    environment:
      - GO111MODULE=on
      - AUTHONE_SERVER_PORT=8080
      - AUTHONE_DATABASE_HOST=auth1-mongo
      - AUTHONE_DATABASE_NAME=auth-one
      - AUTHONE_REDIS_ADDR="auth1-redis:6379"
      - AUTHONE_REDIS_PASSWORD=""
      - AUTHONE_HYDRA_PUBLIC_URL=http://hydra:4444
      - AUTHONE_HYDRA_ADMIN_URL=http://hydra:4445
      - AUTHONE_SESSION_NETWORK=tcp
      - AUTHONE_SESSION_ADDRESS=auth1-redis:6379

volumes:
  auth1-mongo:
    external: true
  auth1-redis:
    external: true
  auth1-postgres:
    external: true

networks:
  subnet:
    external: true
