log_level: debug
admin_handler_prefix: /centrifugo/admin
websocket_handler_prefix: /centrifugo/websocket

proxy_connect_endpoint: http://auth1:8080/centrifugo/auth
proxy_connect_timeout: 1
proxy_refresh_endpoint: http://auth1:8080/centrifugo/refresh
proxy_refresh_timeout: 1

api_key: "insecure"

namespaces:
  - name: "launcher"
    token_hmac_secret_key: insecure