Api:
  Port: 8080
  Debug: true
  TimeoutRead: 15
  TimeoutWrite: 5
Logger:
  Level: "debug"
Database:
  Host: "127.0.0.1"
  Database: "auth-one"
  User: ""
  Password: ""
Session:
  Database: "auth-one"
  Table: "session"
  Secret: "secretkey"
  Name: "sessid"
  MaxAge: 3600
  EnsureTTL: true
Redis:
  Addr: "127.0.0.1:6379"
  Password: ""
Kubernetes:
  Service:
    Host: ""
Hydra:
  PublicURL: "http://127.0.0.1:4444"
  AdminURL: "http://127.0.0.1:4445"
