token_hmac_secret_key: "insecure"
api_key: "insecure"
log_level: debug
proxy_connect_endpoint: http://auth1:8080/centrifugo/auth
proxy_connect_timeout:  1
proxy_refresh_endpoint: http://auth1:8080/centrifugo/refresh
proxy_refresh_timeout:  1