{{- if .Values.enableHydra }}
kind: Service
apiVersion: v1
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  type: ClusterIP
  selector:
    app: hydra
  ports:
    - name: publicsvc
      port: 4444
      targetPort: 4444
      protocol: TCP
    - name: internalsvc
      port: 4445
      targetPort: 4445
      protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hydra
  labels:
    app: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      name: hydra
      labels:
        app: hydra
    spec:
      #volumes:
        #- name: hydra-data
        #  persistentVolumeClaim:
        #    claimName: hardy-clownfish-hydra
        #- name: hydra-secret
        #  secret:
        #    secretName: hydra-secret
      initContainers:
      - name: hydra-migrate
        #image: oryd/hydra:v0.11.14-alpine
        image: "oryd/hydra:v1.0.0-rc.6_oryOS.10-alpine"
        command: ["hydra", "migrate", "sql", "-e"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: p1auth1hydra-env
              key: DATABASE_URL
        - name: LOG_LEVEL
          value: debug
      containers:
        - name: hydra
          #image: oryd/hydra:v0.11.14-alpine
          image: "oryd/hydra:v1.0.0-rc.6_oryOS.10-alpine"
          imagePullPolicy: Always
          command: ["hydra", "serve","all", "--dangerous-force-http"]
          #volumeMounts:
          #  - name: hydra-data
          #    mountPath: /root
          ports:
            - name: publicsvc
              containerPort: 4444
            - name: internalsvc
              containerPort: 4445
          env:
          {{- if .Values.enableHydraDebug }}
          - name: TRACING_PROVIDER
            value: jaeger
          - name: TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL
            value: "http://jaeger-agent:5778/sampling"
          - name: TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS
            value: "jaeger-agent:6831"
          - name: TRACING_PROVIDER_JAEGER_SAMPLING_TYPE
            value: "const"
          - name: TRACING_PROVIDER_JAEGER_SAMPLING_VALUE
            value: "1"
          {{- end }}
          - name: OAUTH2_LOGOUT_URL
            value: "/oauth2/logout"
          - name: BCRYPT_COST
            value: "8"
          - name: LOG_FORMAT
            value: "json"
          - name: DISABLE_TELEMETRY
            value: "1"
          {{- range .Values.hydra.env }}
          - name: {{ . }}
            valueFrom:
              secretKeyRef:
                name: p1auth1hydra-env
                key: {{ . }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /.well-known/jwks.json
              port: 4444
            initialDelaySeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /.well-known/jwks.json
              port: 4444
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 5

#          resources:
#            requests:
#              cpu: 100m
#              memory: 128Mi
{{- end }}
