{{- $endpoint := .Values.backend -}}
{{- $hydraSvc := "hydra-external"}}
{{- if eq .Release.Name "qilin-p1auth1" }}
{{- $hydraSvc := "hydra-external-qilin"}}
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: {{ .Release.Name }}
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/oauth2/userinfo(.*)$ /userinfo$1 break;
spec:
  tls:
    - hosts:
        - {{printf "%s%s" .Values.ingress.hostnamePrefix .Values.ingress.hostname }}
      secretName: {{ .Release.Name}}-ssl-secret
  rules:
    - host: {{printf "%s%s" .Values.ingress.hostnamePrefix .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ $endpoint.service.port }}
          - path: /userinfo
            backend:
              serviceName: {{ $hydraSvc }}
              servicePort: 4444
          - path: /oauth2/auth
            backend:
              serviceName: {{ $hydraSvc }}
              servicePort: 4444
          - path: /oauth2/token
            backend:
              serviceName: {{ $hydraSvc }}
              servicePort: 4444
          - path: /oauth2/revoke
            backend:
              serviceName: {{ $hydraSvc }}
              servicePort: 4444
          - path: /oauth2/userinfo
            backend:
              serviceName: {{ $hydraSvc }}
              servicePort: 4444
          - path: /.well-known/jwks.json
            backend:
              serviceName: {{ $hydraSvc }}
              servicePort: 4444
